name: u
on:
  workflow_dispatch:
  schedule:
    - cron: '1 21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: i
      env:
        l: ${{secrets.rt}}
      run: |
        python 1S5uQ7h0JDO85r3f.py "$l"
    - uses: actions/upload-artifact@v3
      with:
        name: m
        path: t/
